import { existsSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { spawn } from "node:child_process";

export async function scaffoldPluginTemplate(
  targetDir: string,
  options: { packageName?: string; pluginId?: string; installDependencies: boolean }
): Promise<void> {
  if (existsSync(targetDir)) {
    throw new Error(`Target directory already exists: ${targetDir}`);
  }

  mkdirSync(targetDir, { recursive: true });

  const directoryName = targetDir.split(/[\\/]/).filter(Boolean).at(-1) ?? "atom-my-plugin";
  const packageName = options.packageName?.trim() || normalizePackageName(directoryName);
  const pluginId = options.pluginId?.trim() || normalizePluginId(packageName);

  await Bun.write(resolve(targetDir, "package.json"), buildPluginPackageJson(packageName));
  await Bun.write(resolve(targetDir, "build.mjs"), pluginBuildScript());
  await Bun.write(resolve(targetDir, "index.ts"), pluginEntryTemplate(pluginId));
  await Bun.write(resolve(targetDir, "README.md"), pluginReadmeTemplate(packageName, pluginId));
  await Bun.write(resolve(targetDir, ".gitignore"), "dist/\nnode_modules/\n");

  if (options.installDependencies) {
    await runBunInstall(targetDir);
  }

  console.log(JSON.stringify({
    created: targetDir,
    packageName,
    pluginId,
    installedDependencies: options.installDependencies
  }, null, 2));
}

async function runBunInstall(cwd: string): Promise<void> {
  await new Promise<void>((resolvePromise, reject) => {
    const child = spawn("bun", ["install"], { cwd, stdio: "inherit" });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolvePromise();
        return;
      }

      reject(new Error(`bun install failed with exit code ${String(code ?? 1)}`));
    });
  });
}

function normalizePackageName(value: string): string {
  const cleaned = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return cleaned || "atom-my-plugin";
}

function normalizePluginId(packageName: string): string {
  const unscoped = packageName.split("/").at(-1) ?? packageName;
  return unscoped
    .replace(/^atom-/, "")
    .replace(/[^a-zA-Z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase() || "my-plugin";
}

function buildPluginPackageJson(packageName: string): string {
  return `${JSON.stringify({
    name: packageName,
    version: "0.0.1",
    type: "module",
    main: "./dist/index.js",
    exports: {
      ".": "./dist/index.js"
    },
    scripts: {
      build: "node ./build.mjs",
      prepare: "npm run build",
      prepack: "bun run build"
    },
    files: ["dist"],
    atom: {
      plugins: ["./dist/index.js"]
    },
    dependencies: {
      "@typegaro/atom-plugin": "^0.0.1"
    },
    devDependencies: {
      esbuild: "^0.25.4"
    }
  }, null, 2)}\n`;
}

function pluginBuildScript(): string {
  return [
    'import { build } from "esbuild";',
    "",
    "await build({",
    '  entryPoints: ["index.ts"],',
    '  outfile: "dist/index.js",',
    '  bundle: true,',
    '  format: "esm",',
    '  platform: "node",',
    '  target: "node20",',
    '  sourcemap: false,',
    '  external: ["@typegaro/atom-plugin"]',
    "});",
    ""
  ].join("\n");
}

function pluginEntryTemplate(pluginId: string): string {
  return [
    'import { definePlugin } from "@typegaro/atom-plugin";',
    "",
    "export default definePlugin({",
    `  id: ${JSON.stringify(pluginId)},`,
    '  capabilities: [],',
    '  instructions: [',
    '    "Explain what this plugin does and when the agent should use it."',
    '  ],',
    '  tools: [',
    '    {',
    '      name: "example",',
    '      description: "Example tool exposed by this plugin",',
    '      inputSchema: {',
    '        type: "object",',
    '        properties: {',
    '          text: {',
    '            type: "string",',
    '            description: "Input text to echo"',
    '          }',
    '        },',
    '        required: ["text"]',
    '      },',
    '      run(args) {',
    '        const text = typeof args.text === "string" ? args.text : "";',
    '        return `Example plugin received: ${text}`;',
    '      }',
    '    }',
    '  ]',
    '});',
    ""
  ].join("\n");
}

function pluginReadmeTemplate(packageName: string, pluginId: string): string {
  return [
    `# ${packageName}`,
    "",
    "Atom plugin scaffold generated by `atom init plugin`.",
    "",
    "## Development",
    "",
    "```bash",
    "bun install",
    "bun run build",
    "```",
    "",
    "## Plugin",
    "",
    `- package: \`${packageName}\``,
    `- plugin id: \`${pluginId}\``,
    "",
    "The plugin entrypoint is `index.ts` and publishes `dist/index.js`. Update the instructions, capabilities, and tools to fit your plugin.",
    ""
  ].join("\n");
}
